site_name: AbuseIO 5.0
site_url: https://docs.abuse.io
site_author: AbuseIO Foundation
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - admonition
extra:
    version: 5.0
theme: mkdocs
nav:
- 'Index': 'index.md'
- 'Getting Started':
    - 'Installation': 'installation.md'
    - 'Migrating from 3.x': 'old_version.md'
    - 'Migrating from 4.0': 'upgrading.md'
    - 'Main configuration': 'configuration_main.md'
    - 'Common problems': 'common_problems.md'
- 'User Guide':
    - 'Data collection': 'data_collection.md'
    - 'Notifications': 'notifications.md'
    - 'Subscribing to feeds': 'subscribing_to_feeds.md'
- 'Development Guides':
    - 'Parsers': 'development_parsers.md'
- 'About':
    - 'License': 'license.md'
    - 'Release Notes': 'release_notes.md'
- 'Feature Documentation':
    - 'API Documentation': 'api.md'
    - 'Delegation': 'delegation.md'
    - 'GDPR functionality': 'gdpr.md'
